### ISSUE TITLE
请问，你们的数据集什么时候能发布呀？为什么显示已上传

### ISSUE THREAD

**Issue by xinlong12138** [jxbbb/TOD3Cap#2]

**Comment by ucaszyp** [comment]
今天会发布，上一版上传的有点bug

**Comment by xinlong12138** [comment]
好的，期待发布

**Comment by xinlong12138** [comment]
请问这周能发布吗

**Comment by ucaszyp** [comment]
> 请问这周能发布吗
应该可以访问了

**Comment by xinlong12138** [comment]
好的，非常感谢你们的工作，请给一下权限  cxl.d5235252@gmail.com

**Comment by ucaszyp** [comment]
> 好的，非常感谢你们的工作，请给一下权限 [cxl.d5235252@gmail.com](mailto:cxl.d5235252@gmail.com)

已经设置公开访问
